
sudo: true
dist: bionic
language: c
compiler: gcc
matrix:
  include:
  - env: PG=11
  - env: PG=12
  - env: PG=13
branches:
  only:
   - master
   - /^v\d+\.\d+(\.\d+)?$/
before_install:
  - sudo pg_dropcluster --stop 9.6 main
  - sudo service postgresql stop
  - sudo sed -ri 's/#(create_main_cluster) .*$/\1 = false/' /etc/postgresql-common/createcluster.conf
  - if [ $PG = 13 ]; then sudo sed -i -e "s/main/main $PG/" /etc/apt/sources.list.d/pgdg*.list && sudo apt-get -qq update; fi
  - if ! sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install postgresql-$PG postgresql-server-dev-$PG; then echo; fi
  - sudo pip install --upgrade cpp-coveralls
script:
  - |
    set -e
    export PATH=/usr/lib/postgresql/$PG/bin:$PATH
    sudo PATH=$PATH make USE_PGXS=1 ENABLE_GCOV=1 install
    sudo PATH=$PATH make USE_PGXS=1 ENABLE_GCOV=1 with_llvm=no clean all install
    bash -x test.sh
after_success:
    - coveralls --gcov-options '\-lr'
