name: ubuntu

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  tests:
    runs-on: ubuntu-20.04
    env:
      PG: ${{ matrix.postgres-version }}
    strategy:
      fail-fast: false
      matrix:
        postgres-version:
        - '11'
        - '12'
        - '13'
        - '14'
        - '15'
        - '16'
        - '17'
  
    steps:
    - uses: actions/checkout@v2
    - name: Set up packages
      run: |
        set -e
        # add the official Ubuntu/Debian APT repository for PostgreSQL
        sudo sh -c "echo \"deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main $PG\" > /etc/apt/sources.list.d/pgdg.list"
        curl -Ls https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo apt-get update

        sudo apt-get install --assume-yes --quiet --no-install-suggests --no-install-recommends curl postgresql-common lcov libkrb5-dev

        # forbid creation of a "main" cluster when a new postgresql-x.y server package is installed
        sudo sed -ri 's/#(create_main_cluster) .*$/\1 = false/' /etc/postgresql-common/createcluster.conf

        sudo apt-get --assume-yes --quiet --no-install-suggests --no-install-recommends install postgresql-$PG postgresql-server-dev-$PG
    - name: Download noisia
      run: |
        VERSION=0.1.0
        curl -sL https://github.com/lesovsky/noisia/releases/download/v$VERSION/noisia_${VERSION}_linux_amd64.tar.gz | tar xzv noisia
    - name: Compile and install pg_mon
      run: |
        set -e
        sudo make PG_CONFIG=/usr/lib/postgresql/$PG/bin/pg_config USE_PGXS=1 ENABLE_GCOV=1 install
        sudo make PG_CONFIG=/usr/lib/postgresql/$PG/bin/pg_config USE_PGXS=1 ENABLE_GCOV=1 with_llvm=no clean all install
    - name: Run tests
      run: |
        PATH=/usr/lib/postgresql/$PG/bin:$PATH bash -x test.sh
        if grep -E '(ERROR|FATAL)' test_cluster?/pg_log/postgresql.log | grep -Ev '(no COPY in progress|could not connect to|could not send|the database system is not yet accepting connections|database system is shutting|error reading result of streaming command|database system is starting up|log:noisia)'; then exit 1; fi
    - name: Generate lcov.info
      run: |
        gcov -lr *.[ch]
        lcov --capture --directory . --no-external -o lcov.info
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: lcov.info
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: ${{ matrix.postgres-version }}
        parallel: true

  finish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true